apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pes2ug22cs257/k8s-backend:latest
        ports:
        - containerPort: 8000

        volumeMounts:
        - name: jobs-db-storage
          mountPath: /data

      volumes:
      - name: jobs-db-storage
        persistentVolumeClaim:
          claimName: jobs-db-pvc